Update poofitee

diff --git a/poofitee b/poofitee
--- a/poofitee
+++ b/poofitee
@@ -2694,14 +2694,16 @@ showthis () {
 # integrate with press_a_key?
 rows=24
 cols=80
-! [[ -z "$resizepath" ]] && eval `$resizepath`
-rows=$LINES
-cols=$COLUMNS
 #NOTE: BECAUSE OF THE NEED FOR tput IN THIS FUNCTION, WE MUST NOT REDIRECT STDERR OF THE CALLING STATEMENT TO THIS FUNCTION
 # THEREFORE THE WHIPLOG ANSWER WILL BE CONTROLLED WITHIN HERE, THE FILE NAME IS THEN HARDCODED BOTH HERE AND IN THE CALLER
-if [[ -z "$resizepath" ]] && ! [[ -z "$tputpath" ]];then
+if ! [[ -z "$tputpath" ]];then
     rows="$($tputpath lines)"
     cols="$(($($tputpath cols)))"
+fi
+if [[ -z "$tputpath" ]] && ! [[ -z "$resizepath" ]];then # Resizing tested slower that using tput
+    eval `$resizepath`
+   rows=$LINES
+   cols=$COLUMNS
 fi
 maxwidthforwhiplogbox=$((cols - 8))
 title="$(! [[ -z "$dialogpath" ]] && printf "\\Zb\\Z1")$3"
@@ -2777,6 +2779,7 @@ colors=$([[ -z "$whiptailpath" ]] && printf -- "--colors")
                 printf "$line"; \
             done; \
         )" $(($rowsfordialog $(! [[ -z "$whiptailpath" ]] && printf -- "+ 4 "))) $maxwidthforwhiplogbox 2>/tmp/fifos_and_temp_files_for_poofitee_installer/answergui
+        ! [[ "$?" == "0" ]] && exit
         printf "\n" >> /tmp/fifos_and_temp_files_for_poofitee_installer/answergui
         [[ -z "$whiptailpath" ]] && press_a_key # Would need with infobox
     ;;
@@ -2889,6 +2892,7 @@ colors=$([[ -z "$whiptailpath" ]] && printf -- "--colors")
                 printf "$line"; \
             done; \
         )" $rowsfordialog $maxwidthforwhiplogbox 2>/tmp/fifos_and_temp_files_for_poofitee_installer/answergui
+        ! [[ "$?" == "0" ]] && exit
         printf "\n" >> /tmp/fifos_and_temp_files_for_poofitee_installer/answergui
     ;;
     checklist|checkbox)
@@ -3075,7 +3079,15 @@ printf -- "$printout" >> /tmp/fifos_and_temp_files_for_poofitee_installer/sandbo
         numoflinesinoutput="$(($(cat /tmp/fifos_and_temp_files_for_poofitee_installer/numoflinesinoutput) + 2))"
         ! [[ -z "$whiptailpath" ]] && numoflinesinoutput="$(($numoflinesinoutput + 2))"
         rm /tmp/fifos_and_temp_files_for_poofitee_installer/numoflinesinoutput
-        [[ $((rows - numoflinesinoutput)) -gt 11 ]] && rowsfordialog=$(($numoflinesinoutput + $(($5 + $([[ -z "$dialogpath" ]] && printf "2" || printf "4"))))) || rowsfordialog=$(($rows - 8)) 
+        if [[ "$5" == "0" ]];then
+            [[ -z "$whiptailpath" ]] && adjust_for_menu="0" || adjust_for_menu="4"
+        else
+            [[ -z "$whiptailpath" ]] && adjust_for_menu="4" || adjust_for_menu="2"
+        fi
+rowsfordialog=$(($numoflinesinoutput + $5 + $adjust_for_menu))
+#        [[ $((rows - numoflinesinoutput)) -gt 11 ]] && rowsfordialog=$(($numoflinesinoutput + $(($5 + $([[ -z "$dialogpath" ]] && printf "2" || printf "4"))))) || rowsfordialog=$(($rows - 8))
+#        [[ $((rows - numoflinesinoutput)) -gt 11 ]] && rowsfordialog=$(($numoflinesinoutput + $(($5 + $([[ -z "$dialogpath" ]] && printf "2" || printf "4"))))) || rowsfordialog=$(($rows - 8))
+# printf "\n$rowsfordialog\n";exit #added 5 lines to min (2), only add 2 when $5 == "0" in dialog, 6 in whiptail when linesinput is low.  Line count high: add 4 to numoflinesinoutput in whiptail, no diff in dialog)
         $whiplogpath $colors --title "$title" --backtitle "$backtitle" \
                 --scrolltext \
                 $([[ -z "$dialogpath" ]] && printf -- "--separate-output") \
@@ -3092,7 +3104,9 @@ printf -- "$printout" >> /tmp/fifos_and_temp_files_for_poofitee_installer/sandbo
                     fi; \
                     printf "$line"; \
                 done; \
-            )"  "$rowsfordialog" $maxwidthforwhiplogbox "${@:5}" 2>/tmp/fifos_and_temp_files_for_poofitee_installer/answergui
+            )"  $(($rowsfordialog)) $maxwidthforwhiplogbox "${@:5}" 2>/tmp/fifos_and_temp_files_for_poofitee_installer/answergui
+#            )"  "$rowsfordialog" $maxwidthforwhiplogbox "${@:5}" 2>/tmp/fifos_and_temp_files_for_poofitee_installer/answergui
+        ! [[ "$?" == "0" ]] && exit
         printf "\n" >> /tmp/fifos_and_temp_files_for_poofitee_installer/answergui
         while IFS= read -r line;do
             index=0
@@ -3382,16 +3396,17 @@ getentpath="$($whereispath $binaryflag getent)";getentpath="${getentpath#*:}";ge
 adduserpath="$(whereis $binaryflag adduser)";adduserpath="${adduserpath#*:}";adduserpath="${adduserpath# }";adduserpath="${adduserpath%% *}"
 [[ -z "$adduserpath" ]] && adduserpath="$(whereis $binaryflag useradd)";adduserpath="${adduserpath#*:}";adduserpath="${adduserpath# }";adduserpath="${adduserpath%% *}"
 for pgm in ifconfig uniq find tail xargs getent adduser;do
-   if [[ -z "$(eval printf -- "\$$pgm""path" 2>/dev/null)" ]];then
+    if [[ -z "$(eval printf -- "\$$pgm""path" 2>/dev/null)" ]];then
         localwarning+="\n$pgm needs to be installed\n"
     fi
 done
 if ! [[ -z "$localwarning" ]];then
-    localwarning="<center>Your operating system is not entirely adequate:\n\n""$localwarning""$([[ -z "$whiptailpath" ]] && printf -- "\n\npress any key, Ctrl-c aborts....")"
+    localwarning="<center>Your operating system is not entirely adequate:\n\n""$localwarning" # "$([[ -z "$whiptailpath" ]] && printf -- "\n\npress any key, Ctrl-c aborts....")"
     localbacktitle="Deficiency Notice  POOFITEE  $version"
-    showthis "$localwarning" msgbox "YOUR COOPERATION OR ATTENTION IS NEEDED" "$localbacktitle" 1
+    showthis "$localwarning" msgbox "YOUR COOPERATION OR ATTENTION IS NEEDED" "$localbacktitle" 0 -- "" ""
 #    ! [[ -z "$dialogpath" ]] && read -sn1;read -rst 0.001 -n3 discard #Need for this line depends on which box is utilized
 fi
+
 until ! [[ -z "$sudopath" ]];do
     showthis "The actual sudo command is necessary for several aspects of this installer, \
 but it cannot be found.  Please install it before continuing.  Use another window or \
